// Checkpoint data for SBG Route 1 — William Carey Amazing Race
// Content, maps and board photos below are taken directly from each
// CPn/CPn Checkpoint Guide.docx (Location Map, Where to Find the Board,
// The Board, Where the Hidden Word Is). Answers are taken from
// "William Carey Passage.txt" (Checkpoint Keywords Edition), which is the
// authoritative answer key for this route.
window.CP_DATA = {
  CP1: {
    id: "CP1",
    title: "Checkpoint 1 — Burmese Banyan",
    subtitle: "near Swan Lake Gazebo",
    mapImg: "images/cp1-map.jpg",
    mapCaption: "CP1 location marked in red — Swan Lake Gazebo.",
    directions: "Head to the Swan Lake Gazebo, at the southern tip of Swan Lake. Beside the gazebo stands the “Swing Me Mama” sculpture. Right next to the sculpture is a large heritage tree — the Burmese Banyan (Ficus kurzii). The board you need is the heritage tree plaque mounted on a stand at the base of this tree.",
    pathImgs: [],
    board: "Burmese Banyan heritage tree plaque",
    boardImg: "images/cp1-board.jpg",
    boardCaption: "Photo: Burmese Banyan heritage tree plaque.",
    hint: "On the board, find the short line directly under the plaque’s title. It starts: “This Heritage Tree is ….” The hidden word is word #5 in that sentence.",
    pattern: "_ _ _ _ _ _ _ _ _",
    answer: "dedicated",
    contributesKeyword: true,
    whatsapp: false
  },
  CP2: {
    id: "CP2",
    title: "Checkpoint 2 — Swan Lake",
    subtitle: "near the “Joy” Sculpture / Tembusu Tree",
    mapImg: "images/cp2-map.jpg",
    mapCaption: "CP2 location marked in red — Swan Lake.",
    directions: "Find an old tree that appears on the back of the Singapore $5 note. Then walk to the “Joy” sculpture on the grass bank beside Swan Lake. On the board, this heritage tree is dedicated to the husband of a 1990s Chinese Mandopop artist, 林里嫔.",
    pathImgs: [
      { src: "images/cp2-extra.jpg", caption: "Clue: the tree is dedicated to the husband of this 1990s Mandopop artist." }
    ],
    board: "Tembusu Tree heritage plaque",
    boardImg: "images/cp2-board.jpg",
    boardCaption: "Photo: Tembusu Tree heritage plaque.",
    hint: "On the board, find the second paragraph on the panel that starts: “A characteristic plant of freshwater swamp…........” Count words from the very first word of that paragraph. The hidden word is word #20 in that paragraph.",
    pattern: "_ _ _ _ _",
    answer: "known",
    contributesKeyword: true,
    whatsapp: false
  },
  CP3: {
    id: "CP3",
    title: "Checkpoint 3 — West Indies Mahogany",
    subtitle: "Orchid Plaza",
    mapImg: "images/cp3-map.jpg",
    mapCaption: "CP3 location marked in red — Orchid Plaza.",
    directions: "Go to Orchid Plaza, where you'll find a sculpture with two words: word (A) + word (B). A: Calculate 100 ÷ 10(2+3) = ? B: Red Bull gives you ____? Opposite the sculpture is the heritage tree — the board you need is its heritage tree plaque.",
    pathImgs: [
      { src: "images/cp3-hint.jpg", caption: "Clue: the sculpture to look for at Orchid Plaza." }
    ],
    board: "West Indies Mahogany heritage tree plaque",
    boardImg: "images/cp3-board.jpg",
    boardCaption: "Photo: West Indies Mahogany heritage tree plaque.",
    hint: "On the board, find the second paragraph on the plaque (the one describing what the tree’s timber is used for). It starts: “It is from this species which the original ‘mahogany’ wood was produced …” Count words from the very first word of that paragraph. The hidden word is word #34 in that paragraph.",
    pattern: "_ _ _ _ _ _ _ _ _ _",
    answer: "instrument",
    contributesKeyword: true,
    whatsapp: false
  },
  CP4: {
    id: "CP4",
    title: "Checkpoint 4 — Vanda Miss Joaquim",
    subtitle: "near Sun Garden, south of the Bandstand",
    mapImg: "images/cp4-map.jpg",
    mapCaption: "CP4 location marked in red — Vanda Miss Joaquim.",
    directions: "Find the board named after our national flower. It is near the Sun Garden and just south of the Bandstand.",
    pathImgs: [],
    board: "Vanda Miss Joaquim plaque",
    boardImg: "images/cp4-board.jpg",
    boardCaption: "Photo: Vanda Miss Joaquim plaque.",
    hint: "On the board, find the first paragraph on the plaque, which tells the story of how the flower was discovered and named. Count words from the very first word of that paragraph. The hidden word is word #53 in that paragraph.",
    pattern: "_ _ _ _ _",
    answer: "years",
    contributesKeyword: true,
    whatsapp: false
  },
  CP5: {
    id: "CP5",
    title: "Checkpoint 5 — The Bandstand",
    subtitle: "Tanglin Core",
    mapImg: "images/cp5-map.jpg",
    mapCaption: "CP5 location marked in red — The Bandstand.",
    directions: "Climb up to the historic gazebo at the Tanglin Core. Find the iconic music stage surrounded by a ring of yellow Samanea saman (Rain Trees) — a popular wedding photo spot. The board is the interpretive plaque mounted near the gazebo.",
    pathImgs: [],
    board: "Bandstand interpretive plaque",
    boardImg: "images/cp5-board.jpg",
    boardCaption: "Photo: Bandstand interpretive plaque.",
    hint: "On the board, find the paragraph in the bottom-right of the plaque, about the ring of Rain Trees surrounding the Bandstand. It starts: “One of the notable landscape …” Count words from the very first word of that paragraph. The hidden word is word #10 in that paragraph.",
    pattern: "_ _ _ _ _",
    answer: "today",
    contributesKeyword: true,
    whatsapp: false
  },
  CP6: {
    id: "CP6",
    title: "Checkpoint 6 — Saraca Stream Trailhead",
    subtitle: "Nature Immersion Trail, near CDL Green Gallery",
    mapImg: "images/cp6-map.jpg",
    mapCaption: "CP6 location marked in red — Saraca Stream Trailhead.",
    directions: "Find the start of the Nature Immersion Trail along Saraca Stream, near the CDL Green Gallery. The board is the trailhead signboard introducing the walk.",
    pathImgs: [],
    board: "Nature Immersion Trail signboard",
    boardImg: "images/cp6-board.jpg",
    boardCaption: "Photo: Nature Immersion Trail signboard.",
    hint: "On the board, find the second paragraph in the left column, which begins by inviting you to follow the trail. It starts: “As you follow this trail, slow down …” Count words from the very first word of that paragraph. The hidden word is word #11 in that paragraph.",
    pattern: "_ _ _ _",
    answer: "life",
    contributesKeyword: true,
    whatsapp: false
  },
  CP7: {
    id: "CP7",
    title: "Checkpoint 7 — Holttum Hall",
    subtitle: "Singapore Botanic Gardens Heritage Museum",
    mapImg: "images/cp7-map.jpg",
    mapCaption: "CP7 location marked in red — Holttum Hall.",
    directions: "Visit the museum inside the conservation building where Professor Eric Holttum, the Gardens’ Director from 1925 to 1949, developed the innovative orchid-breeding technique that enabled the efficient production of healthy seedlings in sterile flasks from a hybrid seed — a technique still used today, which stimulated thriving orchid industries throughout the region. The board is the plaque describing the Hall’s history.",
    pathImgs: [],
    board: "Holttum Hall history plaque",
    boardImg: "images/cp7-board.jpg",
    boardCaption: "Photo: Holttum Hall history plaque.",
    hint: "On the board, find the paragraph about the orchid-breeding discovery made in the building’s laboratory. It starts: “It was in his laboratory …” Count words from the very first word of that paragraph. The hidden word is word #16 in that paragraph.",
    pattern: "_ _ _ _ _ _ _",
    answer: "carried",
    contributesKeyword: true,
    whatsapp: false
  },
  CP8: {
    id: "CP8",
    title: "Checkpoint 8 — CDL Green Gallery",
    subtitle: "“Wishes for Our Future World” marker",
    mapImg: "images/cp8-map.jpg",
    mapCaption: "CP8 location marked in red — CDL Green Gallery.",
    directions: "Visit the first zero-energy gallery in Singapore, opened by Prime Minister Lee Hsien Loong in 2013. Clue: the developer's name is 3 characters — the Roman numerals for 100, 500 and 50. Look for the marker named “Wishes for Our Future World.”",
    pathImgs: [],
    board: "“Wishes for Our Future World” marker",
    boardImg: "images/cp8-board.jpg",
    boardCaption: "Photo: “Wishes for Our Future World” marker.",
    hint: "On the board, find the first body paragraph describing the 120 global citizens on the Antarctic expedition. Count words from the very first word of that paragraph. The hidden word is word #16 in that paragraph.",
    pattern: "_ _ _ _ _ _ _ _",
    answer: "cultures",
    contributesKeyword: true,
    whatsapp: false
  }
};
